name: deasy_pocket
description: A Shared Preference package for internal deasy.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter
  deasy_encryptor:
    path: ../../helper/deasy_encryptor

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint



