name: deasy_responsive
description: Deasy Responsive helps implement a responsive layout by providing helper widgets and extensions.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: