name: deasy_buttons
description: Deasy internal package to provide button widgets
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  deasy_color:
    path: ../../util/deasy_color
  deasy_size_config:
    path: ../../component/deasy_size_config

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint

flutter:
  uses-material-design: true
