name: deasy_logout
description: The internal Deasy's package to support logout.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  deasy_config:
    path: ../../core/deasy_config
  deasy_pocket:
    path: ../deasy_pocket
  deasy_repository:
    path: ../../core/deasy_repository
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_helper:
    path: ../../helper/deasy_helper
  deasy_lint:
    path: ../../dependency/deasy_lint