FROM asia.gcr.io/deasy-testing-325901/android-builder:1.0.0

ARG DEBIAN_FRONTEND=noninteractive
ARG JDK_VERSION=8

RUN apt-get update && apt-get install -y --no-install-recommends openjdk-${JDK_VERSION}-jdk
ENV JAVA_HOME /usr/lib/jvm/java-${JDK_VERSION}-openjdk-amd64

# Setup Android SDK
ARG ANDROID_SDK_VERSION=8092744
ENV ANDROID_SDK_ROOT /opt/android-sdk
RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip
RUN unzip -q sdk-tools.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools && rm sdk-tools.zip
RUN mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest
ENV PATH $PATH:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin

# Install android sdk build tools
ENV ANDROID_PLATFORM_VERSION 31
ENV ANDROID_BUILD_TOOLS_VERSION 32.0.0
#ENV ANDROID_NDK_VERSION 21.3.6528147

RUN yes | sdkmanager "platform-tools" "platforms;android-$ANDROID_PLATFORM_VERSION" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
#RUN yes | sdkmanager "ndk;$ANDROID_NDK_VERSION"
RUN yes | sdkmanager --licenses

# Install Flutter
ENV FLUTTER_HOME=/usr/local/flutter
ENV FLUTTER_VERSION=3.3.9
RUN git clone --depth 1 --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
RUN flutter doctor -v
RUN yes | flutter doctor --android-licenses

# Copy files to container and get dependencies
COPY . /usr/local/bin/app
WORKDIR /usr/local/bin/app
RUN flutter pub get
RUN flutter build apk --debug --flavor dev -t lib/flavor/dev/main_dev.dart
