name: deasy_text_form
description: collection of textForm with easy style.
version: 1.0.0
publish_to: 'none'


environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  deasy_color:
    path: ../../util/deasy_color

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

