// Mocks generated by Mockito 5.3.2 from annotations
// in kreditplus_deasy_mobile/test/modules/agent_fee/controller/agent_fee_detail_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter/material.dart' as _i6;
import 'package:kreditplus_deasy_mobile/bumblebee/modules/agent_fee/models/response_get_agent_fee.dart'
    as _i2;
import 'package:kreditplus_deasy_mobile/bumblebee/modules/agent_fee/repositories/agent_fee_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseGetAgentFee_0 extends _i1.SmartFake
    implements _i2.ResponseGetAgentFee {
  _FakeResponseGetAgentFee_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AgentFeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentFeeRepository extends _i1.Mock
    implements _i3.AgentFeeRepository {
  @override
  _i4.Future<_i2.ResponseGetAgentFee> postGetAgentFee(
    Map<String, dynamic>? requestBody,
    String? eventName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postGetAgentFee,
          [
            requestBody,
            eventName,
          ],
        ),
        returnValue: _i4.Future<_i2.ResponseGetAgentFee>.value(
            _FakeResponseGetAgentFee_0(
          this,
          Invocation.method(
            #postGetAgentFee,
            [
              requestBody,
              eventName,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.ResponseGetAgentFee>.value(
            _FakeResponseGetAgentFee_0(
          this,
          Invocation.method(
            #postGetAgentFee,
            [
              requestBody,
              eventName,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ResponseGetAgentFee>);
  @override
  _i4.Future<_i5.Uint8List> postDownloadAgentFee(
    String? eventName, {
    Map<String, dynamic>? requestBody,
    _i6.BuildContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postDownloadAgentFee,
          [eventName],
          {
            #requestBody: requestBody,
            #context: context,
          },
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);
}
