name: deasy_size_config
description: The internal Deasy's package to support screen size configuration of a divice.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint