name: stepper
description: Base layout stepper for pengajuan new wg
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  deasy_responsive:
    path: ../../../component/deasy_responsive

  deasy_size_config:
    path: ../../../component/deasy_size_config

  deasy_animation:
    path: ../../../component/deasy_animation

  deasy_color:
    path: ../../../util/deasy_color
  
  additional_documents:
    path: ../additional_documents
  
  verification_customer:
    path: ../verification_customer
  
  newwg_repository:
    path: ../../../core/newwg_repository

  order:
    path: ../order

  newwg:
    path: ../../../../libs/newwg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0