name: deasy_service
description: The internal Deasy's package to support services.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint