// Mocks generated by Mockito 5.3.2 from annotations
// in kreditplus_deasy_mobile/test/modules/merchant_user_management/merchant_user_management_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:deasy_models/deasy_models.dart' as _i2;
import 'package:deasy_repository/deasy_repository.dart' as _i4;
import 'package:flutter/material.dart' as _i6;
import 'package:kreditplus_deasy_mobile/core/config/deep_link_config.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResetPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ResetPasswordResponse {
  _FakeResetPasswordResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRefreshToken_1 extends _i1.SmartFake
    implements _i2.UserRefreshToken {
  _FakeUserRefreshToken_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTokenResponse_2 extends _i1.SmartFake
    implements _i2.GetTokenResponse {
  _FakeGetTokenResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordMailResponse_3 extends _i1.SmartFake
    implements _i2.PasswordMailResponse {
  _FakePasswordMailResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseCheckEmail_4 extends _i1.SmartFake
    implements _i2.ResponseCheckEmail {
  _FakeResponseCheckEmail_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMerchantTypeResponseModel_5 extends _i1.SmartFake
    implements _i2.MerchantTypeResponseModel {
  _FakeMerchantTypeResponseModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseGetDetailRoleManagement_6 extends _i1.SmartFake
    implements _i2.ResponseGetDetailRoleManagement {
  _FakeResponseGetDetailRoleManagement_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoleManagementResponse_7 extends _i1.SmartFake
    implements _i2.RoleManagementResponse {
  _FakeRoleManagementResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoleManagementDataResponse_8 extends _i1.SmartFake
    implements _i2.RoleManagementDataResponse {
  _FakeRoleManagementDataResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoleManagementPermissionResponse_9 extends _i1.SmartFake
    implements _i2.RoleManagementPermissionResponse {
  _FakeRoleManagementPermissionResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteAccountResponse_10 extends _i1.SmartFake
    implements _i2.DeleteAccountResponse {
  _FakeDeleteAccountResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendEmailDeleteAccountResponse_11 extends _i1.SmartFake
    implements _i2.SendEmailDeleteAccountResponse {
  _FakeSendEmailDeleteAccountResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseRegister_12 extends _i1.SmartFake
    implements _i2.ResponseRegister {
  _FakeResponseRegister_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserChangePasswordResponse_13 extends _i1.SmartFake
    implements _i2.UserChangePasswordResponse {
  _FakeUserChangePasswordResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyPasswordResponse_14 extends _i1.SmartFake
    implements _i2.VerifyPasswordResponse {
  _FakeVerifyPasswordResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmptyResponse_15 extends _i1.SmartFake implements _i2.EmptyResponse {
  _FakeEmptyResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDataResponse_16 extends _i1.SmartFake
    implements _i2.UserDataResponse {
  _FakeUserDataResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseLogout_17 extends _i1.SmartFake
    implements _i2.ResponseLogout {
  _FakeResponseLogout_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHistoriesLoginResponse_18 extends _i1.SmartFake
    implements _i2.HistoriesLoginResponse {
  _FakeHistoriesLoginResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_19 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserGetLobTypesResponse_20 extends _i1.SmartFake
    implements _i2.UserGetLobTypesResponse {
  _FakeUserGetLobTypesResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCreateResponse_21 extends _i1.SmartFake
    implements _i2.UserCreateResponse {
  _FakeUserCreateResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_22 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i5.Future<_i2.ResetPasswordResponse> postResetPassword(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? eventName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postResetPassword,
          [
            context,
            requestBody,
            eventName,
          ],
        ),
        returnValue: _i5.Future<_i2.ResetPasswordResponse>.value(
            _FakeResetPasswordResponse_0(
          this,
          Invocation.method(
            #postResetPassword,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.ResetPasswordResponse>.value(
            _FakeResetPasswordResponse_0(
          this,
          Invocation.method(
            #postResetPassword,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ResetPasswordResponse>);
  @override
  _i5.Future<_i2.UserRefreshToken> refreshToken(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.UserRefreshToken>.value(_FakeUserRefreshToken_1(
          this,
          Invocation.method(
            #refreshToken,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserRefreshToken>.value(_FakeUserRefreshToken_1(
          this,
          Invocation.method(
            #refreshToken,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserRefreshToken>);
  @override
  _i5.Future<_i2.GetTokenResponse> getTokenEmail(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTokenEmail,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.GetTokenResponse>.value(_FakeGetTokenResponse_2(
          this,
          Invocation.method(
            #getTokenEmail,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.GetTokenResponse>.value(_FakeGetTokenResponse_2(
          this,
          Invocation.method(
            #getTokenEmail,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.GetTokenResponse>);
  @override
  _i5.Future<_i2.PasswordMailResponse> postPasswordEmail(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? eventName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPasswordEmail,
          [
            context,
            requestBody,
            eventName,
          ],
        ),
        returnValue: _i5.Future<_i2.PasswordMailResponse>.value(
            _FakePasswordMailResponse_3(
          this,
          Invocation.method(
            #postPasswordEmail,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.PasswordMailResponse>.value(
            _FakePasswordMailResponse_3(
          this,
          Invocation.method(
            #postPasswordEmail,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PasswordMailResponse>);
  @override
  _i5.Future<_i2.ResponseCheckEmail> postCheckEmail(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCheckEmail,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.ResponseCheckEmail>.value(_FakeResponseCheckEmail_4(
          this,
          Invocation.method(
            #postCheckEmail,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ResponseCheckEmail>.value(_FakeResponseCheckEmail_4(
          this,
          Invocation.method(
            #postCheckEmail,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ResponseCheckEmail>);
  @override
  _i5.Future<_i2.MerchantTypeResponseModel> getMerchantTypes(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerchantTypes,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.MerchantTypeResponseModel>.value(
            _FakeMerchantTypeResponseModel_5(
          this,
          Invocation.method(
            #getMerchantTypes,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.MerchantTypeResponseModel>.value(
                _FakeMerchantTypeResponseModel_5(
          this,
          Invocation.method(
            #getMerchantTypes,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MerchantTypeResponseModel>);
}

/// A class which mocks [DeepLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkRepository extends _i1.Mock
    implements _i4.DeepLinkRepository {
  @override
  _i5.Future<_i2.DeepLinkResponse?> createLink(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLink,
          [
            context,
            requestBody,
            key,
          ],
        ),
        returnValue: _i5.Future<_i2.DeepLinkResponse?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.DeepLinkResponse?>.value(),
      ) as _i5.Future<_i2.DeepLinkResponse?>);
}

/// A class which mocks [DynamicLinkConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicLinkConfig extends _i1.Mock implements _i7.DynamicLinkConfig {
  @override
  _i5.Future<String> createDynamicLink(
    String? token,
    _i4.DeepLinkRepository? deepLinkRepository,
    String? email,
    String? flag,
    String? route,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDynamicLink,
          [
            token,
            deepLinkRepository,
            email,
            flag,
            route,
          ],
        ),
        returnValue: _i5.Future<String>.value(''),
        returnValueForMissingStub: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  String getPackageName(bool? isAndroid) => (super.noSuchMethod(
        Invocation.method(
          #getPackageName,
          [isAndroid],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
}

/// A class which mocks [RoleManagementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoleManagementRepository extends _i1.Mock
    implements _i4.RoleManagementRepository {
  @override
  _i5.Future<_i2.ResponseGetDetailRoleManagement> getDetailRoles(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailRoles,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.ResponseGetDetailRoleManagement>.value(
            _FakeResponseGetDetailRoleManagement_6(
          this,
          Invocation.method(
            #getDetailRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ResponseGetDetailRoleManagement>.value(
                _FakeResponseGetDetailRoleManagement_6(
          this,
          Invocation.method(
            #getDetailRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ResponseGetDetailRoleManagement>);
  @override
  _i5.Future<_i2.RoleManagementResponse> getRoles(_i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoles,
          [context],
        ),
        returnValue: _i5.Future<_i2.RoleManagementResponse>.value(
            _FakeRoleManagementResponse_7(
          this,
          Invocation.method(
            #getRoles,
            [context],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.RoleManagementResponse>.value(
            _FakeRoleManagementResponse_7(
          this,
          Invocation.method(
            #getRoles,
            [context],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementResponse>);
  @override
  _i5.Future<_i2.RoleManagementResponse> getAllRoles(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRoles,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementResponse>.value(
            _FakeRoleManagementResponse_7(
          this,
          Invocation.method(
            #getAllRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.RoleManagementResponse>.value(
            _FakeRoleManagementResponse_7(
          this,
          Invocation.method(
            #getAllRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementResponse>);
  @override
  _i5.Future<_i2.RoleManagementDataResponse> getRolesById(
    _i6.BuildContext? context,
    String? uuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRolesById,
          [
            context,
            uuid,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementDataResponse>.value(
            _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #getRolesById,
            [
              context,
              uuid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementDataResponse>.value(
                _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #getRolesById,
            [
              context,
              uuid,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementDataResponse>);
  @override
  _i5.Future<_i2.RoleManagementDataResponse> createRoles(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoles,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementDataResponse>.value(
            _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #createRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementDataResponse>.value(
                _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #createRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementDataResponse>);
  @override
  _i5.Future<_i2.RoleManagementDataResponse> updateRoles(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoles,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementDataResponse>.value(
            _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #updateRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementDataResponse>.value(
                _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #updateRoles,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementDataResponse>);
  @override
  _i5.Future<_i2.RoleManagementPermissionResponse> onPermissionRole(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPermissionRole,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementPermissionResponse>.value(
            _FakeRoleManagementPermissionResponse_9(
          this,
          Invocation.method(
            #onPermissionRole,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementPermissionResponse>.value(
                _FakeRoleManagementPermissionResponse_9(
          this,
          Invocation.method(
            #onPermissionRole,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementPermissionResponse>);
  @override
  _i5.Future<_i2.RoleManagementPermissionResponse> offPermissionRole(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #offPermissionRole,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementPermissionResponse>.value(
            _FakeRoleManagementPermissionResponse_9(
          this,
          Invocation.method(
            #offPermissionRole,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementPermissionResponse>.value(
                _FakeRoleManagementPermissionResponse_9(
          this,
          Invocation.method(
            #offPermissionRole,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementPermissionResponse>);
  @override
  _i5.Future<_i2.RoleManagementDataResponse> setActiveRole(
    _i6.BuildContext? context,
    String? uuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveRole,
          [
            context,
            uuid,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementDataResponse>.value(
            _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #setActiveRole,
            [
              context,
              uuid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementDataResponse>.value(
                _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #setActiveRole,
            [
              context,
              uuid,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementDataResponse>);
  @override
  _i5.Future<_i2.RoleManagementDataResponse> setNonActiveRole(
    _i6.BuildContext? context,
    String? uuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNonActiveRole,
          [
            context,
            uuid,
          ],
        ),
        returnValue: _i5.Future<_i2.RoleManagementDataResponse>.value(
            _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #setNonActiveRole,
            [
              context,
              uuid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RoleManagementDataResponse>.value(
                _FakeRoleManagementDataResponse_8(
          this,
          Invocation.method(
            #setNonActiveRole,
            [
              context,
              uuid,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RoleManagementDataResponse>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  @override
  _i5.Future<_i2.DeleteAccountResponse> deleteAccount(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [
            context,
            requestBody,
            id,
          ],
        ),
        returnValue: _i5.Future<_i2.DeleteAccountResponse>.value(
            _FakeDeleteAccountResponse_10(
          this,
          Invocation.method(
            #deleteAccount,
            [
              context,
              requestBody,
              id,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.DeleteAccountResponse>.value(
            _FakeDeleteAccountResponse_10(
          this,
          Invocation.method(
            #deleteAccount,
            [
              context,
              requestBody,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i2.DeleteAccountResponse>);
  @override
  _i5.Future<_i2.SendEmailDeleteAccountResponse> sendEmailDeleteAccount(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailDeleteAccount,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.SendEmailDeleteAccountResponse>.value(
            _FakeSendEmailDeleteAccountResponse_11(
          this,
          Invocation.method(
            #sendEmailDeleteAccount,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.SendEmailDeleteAccountResponse>.value(
                _FakeSendEmailDeleteAccountResponse_11(
          this,
          Invocation.method(
            #sendEmailDeleteAccount,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.SendEmailDeleteAccountResponse>);
  @override
  _i5.Future<_i2.ResponseRegister> userRegister(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? eventName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userRegister,
          [
            context,
            requestBody,
            eventName,
          ],
        ),
        returnValue:
            _i5.Future<_i2.ResponseRegister>.value(_FakeResponseRegister_12(
          this,
          Invocation.method(
            #userRegister,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ResponseRegister>.value(_FakeResponseRegister_12(
          this,
          Invocation.method(
            #userRegister,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ResponseRegister>);
  @override
  _i5.Future<_i2.UserChangePasswordResponse> postApiChangePassword(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
    String? eventName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiChangePassword,
          [
            context,
            requestBody,
            eventName,
          ],
        ),
        returnValue: _i5.Future<_i2.UserChangePasswordResponse>.value(
            _FakeUserChangePasswordResponse_13(
          this,
          Invocation.method(
            #postApiChangePassword,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserChangePasswordResponse>.value(
                _FakeUserChangePasswordResponse_13(
          this,
          Invocation.method(
            #postApiChangePassword,
            [
              context,
              requestBody,
              eventName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserChangePasswordResponse>);
  @override
  _i5.Future<_i2.VerifyPasswordResponse> postApiVerifyPassword(
    _i6.BuildContext? context,
    String? email,
    String? currentPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiVerifyPassword,
          [
            context,
            email,
            currentPassword,
          ],
        ),
        returnValue: _i5.Future<_i2.VerifyPasswordResponse>.value(
            _FakeVerifyPasswordResponse_14(
          this,
          Invocation.method(
            #postApiVerifyPassword,
            [
              context,
              email,
              currentPassword,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.VerifyPasswordResponse>.value(
            _FakeVerifyPasswordResponse_14(
          this,
          Invocation.method(
            #postApiVerifyPassword,
            [
              context,
              email,
              currentPassword,
            ],
          ),
        )),
      ) as _i5.Future<_i2.VerifyPasswordResponse>);
  @override
  _i5.Future<_i2.EmptyResponse> updateFcmUser(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFcmUser,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.EmptyResponse>.value(_FakeEmptyResponse_15(
          this,
          Invocation.method(
            #updateFcmUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.EmptyResponse>.value(_FakeEmptyResponse_15(
          this,
          Invocation.method(
            #updateFcmUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.EmptyResponse>);
  @override
  _i5.Future<_i2.UserDataResponse> getUserById(
    _i6.BuildContext? context,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [
            context,
            id,
          ],
        ),
        returnValue:
            _i5.Future<_i2.UserDataResponse>.value(_FakeUserDataResponse_16(
          this,
          Invocation.method(
            #getUserById,
            [
              context,
              id,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserDataResponse>.value(_FakeUserDataResponse_16(
          this,
          Invocation.method(
            #getUserById,
            [
              context,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserDataResponse>);
  @override
  _i5.Future<_i2.ResponseLogout> logout(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.ResponseLogout>.value(_FakeResponseLogout_17(
          this,
          Invocation.method(
            #logout,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ResponseLogout>.value(_FakeResponseLogout_17(
          this,
          Invocation.method(
            #logout,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ResponseLogout>);
  @override
  _i5.Future<_i2.HistoriesLoginResponse> postApiHistoryLogout(
    _i6.BuildContext? context, {
    int? loginHistoriesId,
    String? appsVersion,
    String? browserType,
    String? browserVersion,
    String? deviceId,
    String? deviceModel,
    String? email,
    bool? isMobile,
    double? latitude,
    double? longitude,
    String? osVersion,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiHistoryLogout,
          [context],
          {
            #loginHistoriesId: loginHistoriesId,
            #appsVersion: appsVersion,
            #browserType: browserType,
            #browserVersion: browserVersion,
            #deviceId: deviceId,
            #deviceModel: deviceModel,
            #email: email,
            #isMobile: isMobile,
            #latitude: latitude,
            #longitude: longitude,
            #osVersion: osVersion,
            #phoneNumber: phoneNumber,
          },
        ),
        returnValue: _i5.Future<_i2.HistoriesLoginResponse>.value(
            _FakeHistoriesLoginResponse_18(
          this,
          Invocation.method(
            #postApiHistoryLogout,
            [context],
            {
              #loginHistoriesId: loginHistoriesId,
              #appsVersion: appsVersion,
              #browserType: browserType,
              #browserVersion: browserVersion,
              #deviceId: deviceId,
              #deviceModel: deviceModel,
              #email: email,
              #isMobile: isMobile,
              #latitude: latitude,
              #longitude: longitude,
              #osVersion: osVersion,
              #phoneNumber: phoneNumber,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.HistoriesLoginResponse>.value(
            _FakeHistoriesLoginResponse_18(
          this,
          Invocation.method(
            #postApiHistoryLogout,
            [context],
            {
              #loginHistoriesId: loginHistoriesId,
              #appsVersion: appsVersion,
              #browserType: browserType,
              #browserVersion: browserVersion,
              #deviceId: deviceId,
              #deviceModel: deviceModel,
              #email: email,
              #isMobile: isMobile,
              #latitude: latitude,
              #longitude: longitude,
              #osVersion: osVersion,
              #phoneNumber: phoneNumber,
            },
          ),
        )),
      ) as _i5.Future<_i2.HistoriesLoginResponse>);
  @override
  _i5.Future<_i2.UserResponse> fetchApiAllUsers(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchApiAllUsers,
          [
            context,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i2.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #fetchApiAllUsers,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #fetchApiAllUsers,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserResponse>);
  @override
  _i5.Future<_i2.UserGetLobTypesResponse> fetchApiLobTypes(
          _i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchApiLobTypes,
          [context],
        ),
        returnValue: _i5.Future<_i2.UserGetLobTypesResponse>.value(
            _FakeUserGetLobTypesResponse_20(
          this,
          Invocation.method(
            #fetchApiLobTypes,
            [context],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserGetLobTypesResponse>.value(
                _FakeUserGetLobTypesResponse_20(
          this,
          Invocation.method(
            #fetchApiLobTypes,
            [context],
          ),
        )),
      ) as _i5.Future<_i2.UserGetLobTypesResponse>);
  @override
  _i5.Future<_i2.UserCreateResponse> postApiCreateUser(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiCreateUser,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.UserCreateResponse>.value(_FakeUserCreateResponse_21(
          this,
          Invocation.method(
            #postApiCreateUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserCreateResponse>.value(_FakeUserCreateResponse_21(
          this,
          Invocation.method(
            #postApiCreateUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserCreateResponse>);
  @override
  _i5.Future<_i2.UserCreateResponse> postApiUpdateUser(
    _i6.BuildContext? context,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiUpdateUser,
          [
            context,
            requestBody,
          ],
        ),
        returnValue:
            _i5.Future<_i2.UserCreateResponse>.value(_FakeUserCreateResponse_21(
          this,
          Invocation.method(
            #postApiUpdateUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UserCreateResponse>.value(_FakeUserCreateResponse_21(
          this,
          Invocation.method(
            #postApiUpdateUser,
            [
              context,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserCreateResponse>);
  @override
  _i5.Future<_i2.EmptyResponse> deleteUser(
    _i6.BuildContext? context,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [
            context,
            id,
          ],
        ),
        returnValue: _i5.Future<_i2.EmptyResponse>.value(_FakeEmptyResponse_15(
          this,
          Invocation.method(
            #deleteUser,
            [
              context,
              id,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.EmptyResponse>.value(_FakeEmptyResponse_15(
          this,
          Invocation.method(
            #deleteUser,
            [
              context,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i2.EmptyResponse>);
}
