name: deasy_text
description: The internal Deasy's package to support text view.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
#  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint

flutter:
  uses-material-design: true
