name: deasy_models
description: The internal Deasy's package for accessing models in deasy
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  deasy_pocket:
    path: ../../util/deasy_pocket

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
