name: Build AAR

on:
  workflow_dispatch:

jobs:

  build_code:
    name: Check out & Setup Flutter
    runs-on: ubuntu-latest
    env:
      environment: DEV
    steps:
      - name: Checkout
        run: echo "WOW"
