name: Speedtest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: speedtest
        run: sudo apt-get install -y speedtest-cli && sudo speedtest-cli
