name: Flutter Build APK

on:
  push:
    branches:
      - mainx
  workflow_dispatch:
#     inputs:
#       environment:
#         type: string
#         default: TEST
#         required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: zip folder
      - uses: vimtor/action-zip@v1
        with:
          files: satu/
          dest: satu.zip
      - uses: vimtor/action-zip@v1
        with:
          files: satu/dua/
          dest: dua.zip
      - uses: vimtor/action-zip@v1
        with:
          files: satu/dua/tiga/
          dest: tiga.zip

      - name: Setup Output zip
        id: artifact
        run: |
          echo "satu=satu.zip" >> $GITHUB_OUTPUT
          echo "dua=dua.zip" >> $GITHUB_OUTPUT
          echo "tiga=tiga.zip" >> $GITHUB_OUTPUT

      - name: Upload AAB to github
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: ${{ steps.artifact.outputs.satu }}
