name: Zip Folder

on:
  push:
    branches:
      - mainx
  workflow_dispatch:
#     inputs:
#       environment:
#         type: string
#         default: TEST
#         required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Upload satu
        uses: actions/upload-artifact@main
        with:
          name: satu
          path: satu/

      - name: Upload dua
        uses: actions/upload-artifact@main
        with:
          name: dua
          path: satu/dua

      - name: Upload tiga
        uses: actions/upload-artifact@main
        with:
          name: tiga
          path: satu/dua/tiga
