name: Zip Folder

on:
  push:
    branches:
      - mainx
  workflow_dispatch:
#     inputs:
#       environment:
#         type: string
#         default: TEST
#         required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: zip folder satu
        uses: vimtor/action-zip@v1
        with:
          files: satu/
          dest: satu.zip

#       - name: zip folder dua
#         uses: vimtor/action-zip@v1
#         with:
#           files: satu/dua/
#           dest: .

#       - name: zip folder tiga
#         uses: vimtor/action-zip@v1
#         with:
#           files: satu/dua/tiga/
#           dest: .

      - name: Setup Output zip
        id: artifact
        run: |
          echo "satu=satu.zip" >> $GITHUB_OUTPUT
#          echo "dua=dua.zip" >> $GITHUB_OUTPUT
#          echo "tiga=tiga.zip" >> $GITHUB_OUTPUT

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.satu }}
          path: satu/
