name: Zip Folder

on:
  push:
    branches:
      - mainx
  workflow_dispatch:
#     inputs:
#       environment:
#         type: string
#         default: TEST
#         required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: satu
          path: satu/
