name: deasy_animation
description: Deasy internal package for animation.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deasy_lint:
    path: ../../dependency/deasy_lint

flutter:
